import type { SectionLesson } from '../../types/lesson';

const anitLesson: SectionLesson = {
  sectionId: 'ANIT',
  title: 'Aviation & Nautical Information Test',
  topics: [
    {
      name: 'Aerodynamics and Flight Principles',
      cards: [
        {
          id: 'anit-lesson-aero-1',
          heading: 'The Four Forces of Flight',
          content:
            'Every aircraft in flight is subject to four forces: lift (upward, generated by the wings), weight (downward, due to gravity), thrust (forward, from engines), and drag (backward, from air resistance). In straight-and-level unaccelerated flight, lift equals weight and thrust equals drag. When any pair becomes unbalanced, the aircraft accelerates in that direction — climbing, descending, speeding up, or slowing down.',
          keyTakeaway:
            'Lift opposes weight, thrust opposes drag. Balanced forces = steady flight.',
        },
        {
          id: 'anit-lesson-aero-2',
          heading: 'How Wings Generate Lift',
          content:
            "Wings generate lift through their airfoil shape — curved on top, flatter on the bottom. Air flowing over the curved upper surface moves faster than air below, creating lower pressure above the wing (Bernoulli's principle). The pressure difference pushes the wing upward. The angle of attack (angle between the wing's chord line and the oncoming air) also contributes by deflecting air downward, producing an upward reaction force (Newton's Third Law).",
          keyTakeaway:
            "Lift comes from pressure difference (Bernoulli's principle) and air deflection (Newton's Third Law).",
        },
        {
          id: 'anit-lesson-aero-3',
          heading: 'Angle of Attack and Stall',
          content:
            'The angle of attack (AOA) is the angle between the wing chord line and the relative wind — not the horizon. Increasing AOA increases lift up to a critical point (typically 15-20 degrees). Beyond this critical angle, airflow separates from the upper wing surface, causing a dramatic loss of lift called a stall. A stall can occur at any airspeed if the critical AOA is exceeded — even in a high-speed dive during a steep pullout.',
          keyTakeaway:
            'Stalls are caused by exceeding the critical angle of attack, not by low airspeed.',
        },
        {
          id: 'anit-lesson-aero-4',
          heading: 'Control Surfaces and Axes of Rotation',
          content:
            'Aircraft rotate around three axes: longitudinal (nose-to-tail, controlled by ailerons for roll), lateral (wingtip-to-wingtip, controlled by elevator for pitch), and vertical (top-to-bottom, controlled by rudder for yaw). Ailerons work in opposite directions — when one goes up, the other goes down. The elevator raises or lowers the nose. The rudder swings the nose left or right. Coordinated use of all three produces smooth, controlled flight.',
          keyTakeaway:
            'Ailerons = roll, elevator = pitch, rudder = yaw. Three axes, three control surfaces.',
        },
        {
          id: 'anit-lesson-aero-5',
          heading: 'Flaps and High-Lift Devices',
          content:
            'Flaps extend from the trailing edge of the wings to increase both lift and drag. By changing the wing\'s camber (curvature) and area, flaps allow the aircraft to fly slower without stalling — essential for takeoff and landing. During landing, the increased drag helps the aircraft descend on a steeper path. Flaps are retracted during cruise for efficiency. Other devices include slats (leading-edge flaps) and spoilers (panels that disrupt lift on the wing).',
          keyTakeaway:
            'Flaps increase lift and drag for slow flight. Extended for takeoff/landing, retracted for cruise.',
        },
      ],
    },
    {
      name: 'Flight Instruments',
      cards: [
        {
          id: 'anit-lesson-inst-1',
          heading: 'Pitot-Static Instruments',
          content:
            "Three instruments use the pitot-static system: the altimeter (measures altitude by sensing atmospheric pressure), the airspeed indicator (measures speed by comparing pitot ram pressure to static pressure), and the vertical speed indicator (shows rate of climb/descent by measuring rate of pressure change). The pitot tube faces forward to capture ram air pressure, while static ports sense ambient pressure. If either becomes blocked (by ice or debris), these instruments give false readings.",
          keyTakeaway:
            'Altimeter, airspeed indicator, and VSI all depend on pitot and/or static pressure.',
        },
        {
          id: 'anit-lesson-inst-2',
          heading: 'Gyroscopic Instruments',
          content:
            'Three instruments use spinning gyroscopes: the attitude indicator (shows pitch and bank relative to the horizon), the heading indicator (shows magnetic heading more reliably than a magnetic compass), and the turn coordinator (shows rate and quality of turns). Gyroscopes maintain their orientation in space due to rigidity in space. They are powered by vacuum pumps or electric motors. If the power source fails, these instruments become unreliable.',
          keyTakeaway:
            'Attitude indicator, heading indicator, and turn coordinator are gyroscope-powered. No power = no reliability.',
        },
        {
          id: 'anit-lesson-inst-3',
          heading: 'The Magnetic Compass',
          content:
            "The magnetic compass is the only instrument that needs no external power — it aligns with Earth's magnetic field. However, it has known errors: turning error (leads when turning from south, lags from north — mnemonic: UNOS), acceleration error (shows north on acceleration, south on deceleration — ANDS), and dip error (caused by magnetic field lines angling into Earth near the poles). Pilots use the heading indicator for stable readings and periodically realign it with the compass.",
          keyTakeaway:
            'The magnetic compass needs no power but has turning, acceleration, and dip errors. Mnemonic: UNOS, ANDS.',
        },
        {
          id: 'anit-lesson-inst-4',
          heading: 'The Instrument Scan',
          content:
            'Instrument pilots use a systematic scan pattern to monitor all instruments efficiently. The most common pattern centers on the attitude indicator — the pilot glances at it, then checks one other instrument, returns to the attitude indicator, checks another, and so on in a radial pattern. This prevents fixating on a single instrument while ensuring all are monitored. The scan rate increases during critical phases like approaches and unusual attitudes.',
          keyTakeaway:
            'Scan radiates from the attitude indicator. Check one instrument, return to center, repeat. Avoid fixation.',
        },
      ],
    },
    {
      name: 'Nautical Knowledge',
      cards: [
        {
          id: 'anit-lesson-naut-1',
          heading: 'Ship Anatomy and Terminology',
          content:
            "The bow is the front of the ship, the stern is the rear. Port is the left side (red navigation light), starboard is the right side (green navigation light). The keel is the structural backbone running along the bottom. Bulkheads are watertight interior walls that divide the ship into compartments for damage control. The bridge is the command center. 'Fore' means toward the bow, 'aft' means toward the stern, and 'amidships' means in the middle.",
          keyTakeaway:
            "Bow = front, stern = rear, port = left (red), starboard = right (green). Keel = backbone, bulkheads = watertight walls.",
        },
        {
          id: 'anit-lesson-naut-2',
          heading: 'Port, Starboard, and Navigation Lights',
          content:
            "Port (left) uses a red light; starboard (right) uses a green light. A white stern light shines aft. These lights tell other vessels which direction you're heading at night. Memory aid: 'port' and 'left' both have 4 letters; port wine is red. If you see another vessel's red light on your right side, it is crossing from your left — you should yield. If you see green on your right, you have the right of way.",
          keyTakeaway:
            "Port = left = red light. Starboard = right = green light. 'Port' and 'left' both have 4 letters.",
        },
        {
          id: 'anit-lesson-naut-3',
          heading: 'Nautical Measurements',
          content:
            'A nautical mile (NM) equals 1,852 meters or approximately 1.15 statute miles. It is based on one minute of latitude, making it natural for chart-based navigation. A knot is one nautical mile per hour. Fathoms measure water depth (1 fathom = 6 feet). Ship displacement is the weight of water displaced, equal to the ship\'s weight (Archimedes\' principle), and is measured in long tons or metric tonnes.',
          keyTakeaway:
            '1 nautical mile = 1.15 statute miles = 1 minute of latitude. 1 knot = 1 NM/hour. 1 fathom = 6 feet.',
        },
        {
          id: 'anit-lesson-naut-4',
          heading: 'Navy Watch System',
          content:
            "The Navy divides the 24-hour day into watches: Middle (0000-0400), Morning (0400-0800), Forenoon (0800-1200), Afternoon (1200-1600), First Dog (1600-1800), Second Dog (1800-2000), and First (2000-0000). Most watches are 4 hours, but the two 2-hour 'dog watches' create an odd number, rotating the schedule daily so sailors don't stand the same watch every day. All times use the 24-hour clock (military time) and UTC (Zulu time).",
          keyTakeaway:
            'Standard watches are 4 hours. Dog watches (2 hours each) rotate the daily schedule. All times in 24-hour UTC.',
        },
      ],
    },
    {
      name: 'Aviation Weather',
      cards: [
        {
          id: 'anit-lesson-wx-1',
          heading: 'Cloud Types and What They Indicate',
          content:
            'Clouds are classified by shape and altitude. Cumulus clouds are puffy, forming in unstable air — tall cumulonimbus produce thunderstorms. Stratus clouds are flat layers in stable air, producing drizzle and low ceilings. Cirrus clouds are thin, wispy, ice-crystal clouds at high altitude, often signaling an approaching front. Nimbus (or nimbo-) means rain-bearing. Altitudes: cirro- = high (above 20,000 ft), alto- = middle (6,500-20,000 ft), no prefix = low (below 6,500 ft).',
          keyTakeaway:
            'Cumulus = puffy/unstable, stratus = flat/stable, cirrus = high/wispy. Nimbus = rain-bearing.',
        },
        {
          id: 'anit-lesson-wx-2',
          heading: 'Front Types and Associated Weather',
          content:
            'A cold front (fast-moving cold air undercutting warm air) brings brief, intense storms followed by rapid clearing. A warm front (slow-moving warm air sliding over cold air) brings gradual cloudiness and prolonged, steady rain. A stationary front stalls in place with persistent clouds and precipitation. An occluded front (cold front overtaking a warm front) produces complex weather combining both characteristics. Cold fronts move fastest and produce the most violent weather.',
          keyTakeaway:
            'Cold fronts = intense, brief storms. Warm fronts = prolonged, steady rain. Occluded = complex mix.',
        },
        {
          id: 'anit-lesson-wx-3',
          heading: 'Visibility Hazards for Pilots',
          content:
            'Fog is the most common visibility hazard — it forms when air temperature equals the dew point. Radiation fog forms on clear, calm nights as the ground cools. Advection fog forms when warm, moist air moves over a cold surface. Aircraft icing (0°C to -20°C in visible moisture) distorts wing shape, reduces lift, increases drag, and adds weight. Wind shear — sudden changes in wind speed or direction — is especially dangerous during takeoff and landing, particularly near thunderstorms (microbursts).',
          keyTakeaway:
            'Fog = most common hazard. Icing occurs 0°C to -20°C. Wind shear is dangerous near the ground.',
        },
        {
          id: 'anit-lesson-wx-4',
          heading: 'Basic Weather Briefing Concepts',
          content:
            "Pilots get weather briefings before every flight. ATIS (Automatic Terminal Information Service) broadcasts current airport conditions on a continuous loop. METARs are routine hourly weather observations (current conditions). TAFs (Terminal Aerodrome Forecasts) predict airport weather for 24-30 hours. VFR requires minimum visibility and cloud clearance; IFR allows instrument-only flight in poor weather. Aviation uses UTC (Zulu time) worldwide to avoid time-zone confusion.",
          keyTakeaway:
            'ATIS = airport broadcast, METAR = current weather, TAF = forecast. All times in UTC (Zulu).',
        },
      ],
    },
  ],
};

export default anitLesson;
